name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile program
      run: g++ -std=c++17 -o bubblesort bubbleSort-5246.cpp

    - name: Run program (non-interactive test)
      run: echo -e "5\n4\n2\n1\n3\n5\n" | ./bubblesort
